### ISSUE TITLE
Claude issues

### ISSUE THREAD

**Issue by jamesleslie-uom** [yzhengfei/ai-coding#50]
Using https://claude.ai I get this error, it used to work. Pressing play in AI Provider config returns "Connection is successful"

{"type":"error","error":{"type":"permission_error","message":"Invalid authorization"}}

Using https://api.anthropic.com, with own API key with credit added returns

max_tokens: Field required

**Comment by jamesleslie-uom** [comment]
I love using Claude to write my git commit messages. It'd be amazing if you could fix these issues

**Comment by yzhengfei** [comment]
Thank you for your feedback.

The `max_tokens` field has been added, you can try this version for now. 
[AI Coding-2024.1.12.zip](https://github.com/user-attachments/files/16522009/AI.Coding-2024.1.12.zip)


Since my Claude account is suspended, I'm unable to verify it. If you encounter any issues, please continue to provide feedback to me, thank you.

**Comment by jamesleslie-uom** [comment]
Thanks for fixing this but now using the new build you provided I get these errors

![image](https://github.com/user-attachments/assets/4eb33d98-2ad9-401a-a313-e6208d8d21b1)

**Comment by yzhengfei** [comment]
Try this version. Contact me anytime if there are any problems. Thanks.
[AI Coding-2024.1.12.zip](https://github.com/user-attachments/files/16540784/AI.Coding-2024.1.12.zip)

**Comment by jamesleslie-uom** [comment]
Cool that works for the Anthropic API but not https://claude.ai but that good enough for now thank for that :)
